# Generated by Django 6.0.3 on 2026-03-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_certification_mapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecertificationmapping',
            old_name='certiification',
            new_name='certification',
        ),
    ]
